export { Home } from './Home'
export { About } from './About'
export { Blog } from './Blog'
export { Projects } from './Projects'
export { Skills } from './Skills'
export { Contact } from './Contact'
export {MainSection} from './MainSection'
